
<div ng-app="">
<div class="hero-titles" style="text-align:center">
  <h1 class="hero-site" style="font-size: 3em">EDOT</h1>
</div>


	<ul class="nav nav-tabs" style="margin-bottom:0px" data-ng-init="ufactors=['1.5','3.72','1.5','5.7','3.3']">
		<li class="active">
			<a href="#tab_1_1" data-toggle="tab">
			3D View </a>
		</li>
		<li>
			<a href="#tab_1_2" data-toggle="tab">
			Plan </a>
		</li>
		<li >
			<a href="#tab_1_3" data-toggle="tab">
			Elevation
			</a>
		</li>
		
		<li>
			<a href="#tab_1_4" data-toggle="tab">
			Glass Properties
			</a>
		</li>
	</ul>
	<div class="tab-content"   style="border:1px solid #ddd;border-top:none;height:985px">
		<div class="ctab-pane fade active in" id="tab_1_1">
					
				<div style="padding:20px;width:90%;margin:auto;height:90%">	
					<canvas id="cvs3"></canvas><br>
					<input id="zoomcvs3" type="range" name="points" min="10" max="100" value="30">
				</div>
		</div>
		<div class="ctab-pane fade" id="tab_1_2">
		        <div style="padding:20px;width:90%;margin:auto;height:90%">	
					<canvas id="cvs1"></canvas><br>			
					<input id="zoomcvs1" type="range" name="points" min="10" max="100" value="70">
				</div>
		</div>
		<div class="ctab-pane fade" id="tab_1_3">
		        <div style="padding:20px;width:90%;margin:auto;height:90%">	
					<canvas id="cvs2"></canvas><br>								
					<input id="zoomcvs2" type="range" name="points" min="10" max="100" value="70">			
				</div>
		</div>
		<div class="ctab-pane fade" id="tab_1_4">
				<div style="padding:20px;width:90%;margin:auto;height:90%">	
  					<canvas id="cvs4" style="float:left"></canvas>								
                     
					<input id="zoomcvs4" type="range" name="points" min="10" max="100" value="50" hidden>
				</div>
		</div>
	</div>


</div>

 <script type="text/javascript" src="<?php echo $this->basePath(); ?>/assets/admin/graph/Cango3D-7v00.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/assets/admin/graph/jquery.js"></script>
	 <script type="text/javascript" src="<?php echo $this->basePath(); ?>/assets/admin/graph/jquery-ui.js"></script>
   
   <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/assets/admin/css/jquery-ui.css">
   <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/assets/admin/css/pure-min.css">
   <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/assets/admin/css/side-menu-old-ie.css">
   <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/assets/admin/css/side-menu.css">
   <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/assets/admin/css/1.11.5.css">
   <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/assets/admin/css/d.css">

<style type="text/css">
  #slider-vertical {
    background: -webkit-linear-gradient(red, green); /* For Safari 5.1 to 6.0 */
    background: -o-linear-gradient(red, green); /* For Opera 11.1 to 12.0 */
    background: -moz-linear-gradient(red, green); /* For Firefox 3.6 to 15 */
    background: linear-gradient(red, green); /* Standard syntax (must be last) */    
  }

  #canvasTable {
     border-collapse: collapse;
  }

  canvas{
    height: 250px;
  }

  
</style>



<script type="text/javascript">

var data = [
         {'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':14987.228089588},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':14987.228089588},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':14987.228089588},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':14987.228089588},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':14987.228089588},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':14987.228089588},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.86955078125,'SHGC':0.2,'Energy (KWh)':14987.26991449},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.86955078125,'SHGC':0.2,'Energy (KWh)':14987.26991449},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.85314453125,'SHGC':0.2,'Energy (KWh)':14987.332943739},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.85314453125,'SHGC':0.2,'Energy (KWh)':14987.332943739},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':14987.441578304},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':14987.441578304},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':14987.441578304},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.8778125,'SHGC':0.2,'Energy (KWh)':14987.501974378},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.8778125,'SHGC':0.2,'Energy (KWh)':14987.501974378},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.828828125,'SHGC':0.2,'Energy (KWh)':14988.087464808},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.894453125,'SHGC':0.2,'Energy (KWh)':14988.247872792},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.894453125,'SHGC':0.2,'Energy (KWh)':14988.247872792},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.8128125,'SHGC':0.2,'Energy (KWh)':14989.187290354},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':14989.246614975},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.928203125,'SHGC':0.2,'Energy (KWh)':14990.801195996},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.928203125,'SHGC':0.2,'Energy (KWh)':14990.801195996},
         		{'group':0,'Orientation (degrees)':11.25,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':14992.755425013},
         		{'group':1,'Orientation (degrees)':11.25,'Aspect Ratio':0.962578125,'SHGC':0.2,'Energy (KWh)':14995.126834753},
         		{'group':1,'Orientation (degrees)':5.625,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15095.463869034},
         		{'group':1,'Orientation (degrees)':5.625,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15095.463869034},
         		{'group':1,'Orientation (degrees)':16.875,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15126.894286935},
         		{'group':1,'Orientation (degrees)':16.875,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15126.894286935},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':15144.393689245},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':15144.393689245},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':15144.393689245},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':15144.393689245},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':15144.393689245},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':1,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15144.616245736},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15145.814863239},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15145.814863239},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15145.814863239},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15145.814863239},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':1.0153125,'SHGC':0.2,'Energy (KWh)':15146.474541599},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.8778125,'SHGC':0.2,'Energy (KWh)':15148.785154135},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':1.05125,'SHGC':0.2,'Energy (KWh)':15149.870949933},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':1.05125,'SHGC':0.2,'Energy (KWh)':15149.870949933},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15150.955348991},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15150.955348991},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':15153.528359302},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':15153.528359302},
         		{'group':2,'Orientation (degrees)':0.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':15153.528359302},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':15153.528359302},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':0.828828125,'SHGC':0.2,'Energy (KWh)':15156.380362078},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':3,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':15160.013522073},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':4,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':15194.060415831},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.828828125,'SHGC':0.2,'Energy (KWh)':15206.397915423},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15210.462406546},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.861328125,'SHGC':0.2,'Energy (KWh)':15210.462406546},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15219.177484242},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15219.177484242},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.9453125,'SHGC':0.2,'Energy (KWh)':15226.509668195},
         		{'group':5,'Orientation (degrees)':22.5,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15235.128891698},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.445,'SHGC':0.2,'Energy (KWh)':15243.9164211},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.445,'SHGC':0.2,'Energy (KWh)':15243.9164211},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.445,'SHGC':0.2,'Energy (KWh)':15243.9164211},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.445,'SHGC':0.2,'Energy (KWh)':15243.9164211},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.445,'SHGC':0.2,'Energy (KWh)':15243.9164211},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.62,'SHGC':0.2,'Energy (KWh)':15306.364652101},
         		{'group':5,'Orientation (degrees)':33.75,'Aspect Ratio':0.91125,'SHGC':0.2,'Energy (KWh)':15391.489390529},
         		{'group':5,'Orientation (degrees)':45.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15594.570997611},
         		{'group':5,'Orientation (degrees)':45.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':15594.570997611},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.25,'Energy (KWh)':15675.041915319},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.25,'Energy (KWh)':15684.94794893},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':1.445,'SHGC':0.25,'Energy (KWh)':15718.761570378},
         		{'group':5,'Orientation (degrees)':0.0,'Aspect Ratio':0.72,'SHGC':0.25,'Energy (KWh)':15795.38651059},
         		{'group':5,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.2,'Energy (KWh)':15876.107869473},
         		{'group':5,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.2,'Energy (KWh)':15876.107869473},
         		{'group':5,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.2,'Energy (KWh)':15876.107869473},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':15887.162256924},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':15887.162256924},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':15887.162256924},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':15887.162256924},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':15887.162256924},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.28,'Energy (KWh)':15890.821604386},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.28,'Energy (KWh)':15890.821604386},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':15906.506167712},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':15906.506167712},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':1.62,'SHGC':0.28,'Energy (KWh)':15951.499027069},
         		{'group':6,'Orientation (degrees)':0.0,'Aspect Ratio':0.845,'SHGC':0.28,'Energy (KWh)':15953.925134117},
         		{'group':6,'Orientation (degrees)':180.0,'Aspect Ratio':0.5,'SHGC':0.2,'Energy (KWh)':16031.87905666},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':6,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.2,'Energy (KWh)':16032.611849319},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.5,'SHGC':0.25,'Energy (KWh)':16043.481685349},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.5,'SHGC':0.25,'Energy (KWh)':16043.481685349},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.5,'SHGC':0.25,'Energy (KWh)':16043.481685349},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.5,'SHGC':0.25,'Energy (KWh)':16043.481685349},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.28,'Energy (KWh)':16102.792829208},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.28,'Energy (KWh)':16102.792829208},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.605,'SHGC':0.25,'Energy (KWh)':16129.778162493},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':16198.349523843},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':16198.349523843},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':16198.349523843},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':16198.349523843},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':16198.349523843},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.2,'Energy (KWh)':16198.349523843},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.28,'Energy (KWh)':16230.857620981},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.28,'Energy (KWh)':16230.857620981},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.28,'Energy (KWh)':16230.857620981},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.28,'Energy (KWh)':16230.857620981},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.25,'Energy (KWh)':16243.184720305},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.25,'Energy (KWh)':16243.184720305},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.25,'Energy (KWh)':16243.184720305},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':16377.739339644},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':16377.739339644},
         		{'group':7,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':16377.739339644},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':16377.739339644},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':16377.739339644},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.28,'Energy (KWh)':16377.739339644},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':16382.703598032},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':16382.703598032},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.2,'Energy (KWh)':16382.703598032},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.25,'Energy (KWh)':16385.395399825},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.25,'Energy (KWh)':16536.583055883},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':16537.190731745},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.28,'Energy (KWh)':16537.190731745},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':16566.997453405},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':16566.997453405},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.2,'Energy (KWh)':16566.997453405},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.25,'Energy (KWh)':16704.570066944},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.28,'Energy (KWh)':16707.939569085},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.28,'Energy (KWh)':16707.939569085},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.28,'Energy (KWh)':16707.939569085},
         		{'group':8,'Orientation (degrees)':180.0,'Aspect Ratio':1.445,'SHGC':0.25,'Energy (KWh)':16732.319339137},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.445,'SHGC':0.2,'Energy (KWh)':16760.291158619},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.62,'SHGC':0.2,'Energy (KWh)':16958.30861834},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.62,'SHGC':0.28,'Energy (KWh)':17067.764753572},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.805,'SHGC':0.2,'Energy (KWh)':17159.657470891},
         		{'group':8,'Orientation (degrees)':90.0,'Aspect Ratio':1.805,'SHGC':0.28,'Energy (KWh)':17254.25736535},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':1.62,'SHGC':0.25,'Energy (KWh)':17257.118245309},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':2,'SHGC':0.28,'Energy (KWh)':17444.269417593},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':2,'SHGC':0.25,'Energy (KWh)':17651.888240095},
         		{'group':9,'Orientation (degrees)':0.0,'Aspect Ratio':1.805,'SHGC':0.67,'Energy (KWh)':19154.902118335},
         		{'group':9,'Orientation (degrees)':0.0,'Aspect Ratio':2,'SHGC':0.67,'Energy (KWh)':19174.588881327},
         		{'group':9,'Orientation (degrees)':0.0,'Aspect Ratio':1.28,'SHGC':0.67,'Energy (KWh)':19290.799988224},
         		{'group':9,'Orientation (degrees)':0.0,'Aspect Ratio':1.125,'SHGC':0.67,'Energy (KWh)':19389.079391972},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.67,'Energy (KWh)':19462.344026085},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.67,'Energy (KWh)':19462.344026085},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.72,'SHGC':0.67,'Energy (KWh)':19462.344026085},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.67,'Energy (KWh)':19475.536505187},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.67,'Energy (KWh)':19475.536505187},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.845,'SHGC':0.67,'Energy (KWh)':19475.536505187},
         		{'group':9,'Orientation (degrees)':0.0,'Aspect Ratio':0.98,'SHGC':0.67,'Energy (KWh)':19515.725703989},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.98,'SHGC':0.67,'Energy (KWh)':19517.885345106},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':1.125,'SHGC':0.67,'Energy (KWh)':19581.539584079},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':0.5,'SHGC':0.67,'Energy (KWh)':19586.802653917},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.67,'Energy (KWh)':19676.042684824},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.67,'Energy (KWh)':19676.042684824},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':1.28,'SHGC':0.67,'Energy (KWh)':19676.042684824},
         		{'group':9,'Orientation (degrees)':90.0,'Aspect Ratio':1.445,'SHGC':0.67,'Energy (KWh)':19788.823726799},
         		{'group':9,'Orientation (degrees)':180.0,'Aspect Ratio':1.28,'SHGC':0.67,'Energy (KWh)':19846.727048813}
         		];

  minValArray = [];
  maxValArray = [];
  azimuthVals = [];
  wwrVals = [];
  aspectVals = [];
  overhangVals = [];

  function min(a,b){
    if(a<b)
      return a;
    return b;
  }
  function max(a,b){
    if(a>b)
      return a;
    return b;
  }

  function locateMin(data){
    minValArray = data[0];
    maxValArray = data[0];
    for (var i = data.length - 1; i >= 0; i--) {
      minValArray.azimuth = min(minValArray.azimuth, data[i].azimuth);
      minValArray.wwr = min(minValArray.wwr, data[i].wwr);
      minValArray.overhang = min(minValArray.overhang, data[i].overhang);
      minValArray.aspectRatio = min(minValArray.aspectRatio, data[i].aspectRatio);
      minValArray.energy = min(minValArray.energy, data[i].energy);

      maxValArray.azimuth = max(maxValArray.azimuth, data[i].azimuth);
      maxValArray.wwr = max(maxValArray.wwr, data[i].wwr);
      maxValArray.overhang = max(maxValArray.overhang, data[i].overhang);
      maxValArray.aspectRatio = max(maxValArray.aspectRatio, data[i].aspectRatio);
      maxValArray.energy = max(maxValArray.energy, data[i].energy);
    };
  }

  function findDistinct(data){
    for (var i = data.length - 1; i >= 0; i--) {
      var flag=0;
      for (var j = azimuthVals.length - 1; j >= 0; j--) {
        if(azimuthVals[j]===data[i].azimuth){
          flag=1;
          break;
        }
      };
      if(flag===0){
        azimuthVals.push(data[i].azimuth);
      }
      flag=0;

      for (var j = wwrVals.length - 1; j >= 0; j--) {
        if(wwrVals[j]===data[i].wwr){
          flag=1;
          break;
        }
      };
      if(flag===0){
        wwrVals.push(data[i].wwr);
      }
      flag=0;

      for (var j = aspectVals.length - 1; j >= 0; j--) {
        if(aspectVals[j]===data[i].aspectRatio){
          flag=1;
          break;
        }
      };
      if(flag===0){
        aspectVals.push(data[i].aspectRatio);
      }

      flag=0;
      for (var j = overhangVals.length - 1; j >= 0; j--) {
        if(overhangVals[j]===data[i].overhang){
          flag=1;
          break;
        }
      };
      if(flag===0){
        overhangVals.push(data[i].overhang);
      }
      flag=0;
    };
    azimuthVals.sort(function(a, b){return a-b});
    wwrVals.sort(function(a, b){return a-b});
    overhangVals.sort(function(a, b){return a-b});
    aspectVals.sort(function(a, b){return a-b});
  }

  storeData=data;
  locateMin(storeData);
  findDistinct(storeData);

  $("canvas").width($("#firstTd").width());
  $("#cvs4").width($("#firstTd").width()/2);
	$("#slider-vertical").css("height", $("#energyTd").height()-100);

  $( "#slider-azimuth" ).slider({
    orientation: "horizontal",
    range: true,
    min: 0,
    max: 4,
    values: [0, 4],
    slide: function( event, ui ) {
      console.log(ui);
      filterData("azimuth", [ azimuthVals[ui.values[0]], azimuthVals[ui.values[1]] ]);
      $($("#slider-azimuth").children()[0]).html(azimuthVals[ui.values[0]]);
      $($("#slider-azimuth").children()[1]).html(azimuthVals[ui.values[1]]);
    }
  });
  $($("#slider-azimuth").children()[0]).html(azimuthVals[0]);
  $($("#slider-azimuth").children()[1]).html(azimuthVals[4]);
  $( "#slider-aspectratio" ).slider({
    orientation: "horizontal",
    range: true,
    min: 0,
    max: 4,
    values: [0, 4],
    slide: function( event, ui ) {
      console.log(ui);
      filterData("aspectRatio", [ aspectVals[ui.values[0]], aspectVals[ui.values[1]] ]);
      $($("#slider-aspectratio").children()[0]).html(aspectVals[ui.values[0]]);
      $($("#slider-aspectratio").children()[1]).html(aspectVals[ui.values[1]]);
    }
  });
  $($("#slider-aspectratio").children()[0]).html(aspectVals[0]);
  $($("#slider-aspectratio").children()[1]).html(aspectVals[1]);
  $( "#slider-wwr" ).slider({
    orientation: "horizontal",
    range: true,
    min: 0,
    max: 4,
    values: [0, 4],
    slide: function( event, ui ) {
      console.log(ui);
      filterData("wwr", [ wwrVals[ui.values[0]], wwrVals[ui.values[1]] ]);
      $($("#slider-wwr").children()[0]).html(wwrVals[ui.values[0]]);
      $($("#slider-wwr").children()[1]).html(wwrVals[ui.values[1]]);
    }
  });
  $($("#slider-wwr").children()[0]).html(wwrVals[0]);
  $($("#slider-wwr").children()[1]).html(wwrVals[4]);
  $( "#slider-overhang" ).slider({
    orientation: "horizontal",
    range: true,
    min: 0,
    max: 4,
    values: [0, 4],
    slide: function( event, ui ) {
      console.log(ui);
      filterData("overhang", [ overhangVals[ui.values[0]], overhangVals[ui.values[1]] ]);
      $($("#slider-overhang").children()[0]).html(overhangVals[ui.values[0]]);
      $($("#slider-overhang").children()[1]).html(overhangVals[ui.values[1]]);
    }
  });
  $($("#slider-overhang").children()[0]).html(overhangVals[0]);
  $($("#slider-overhang").children()[1]).html(overhangVals[4]);

  function updateshgc(shgc){
    var ufactor, vlt;
    if(shgc===0.25){
      ufactor=1.5;
      vlt=0.50;
    }
    if(shgc===0.28){
      ufactor=3.72;
      vlt=0.27;
    }
    if(shgc===0.67){
      ufactor=5.7;
      vlt=0.67;
    }
    if(shgc===0.20){
      ufactor=1.5;
      vlt=0.35;
    }
    if(shgc===0.85){
      ufactor=3.3;
      vlt=0.85;
    }
    $("#curshgc").html(shgc);
    $("#curvlt").html(vlt);
    $("#curufactor").html(ufactor+" W/m<sup>2</sup>-K");
  }

	var totalArea = "<?php echo 50; ?>";

  function init(data){
    if(data.length===0){
      return ;
    }
    var initval=Math.floor(data.length/2);
    var energyIndex = initval;
    console.log(data);
    console.log(data.length/2);
    console.log("energyIndex " + energyIndex);

    $( "#slider-vertical" ).slider({
      orientation: "vertical",
      range: false,
      min: 0,
      max: data.length-1,
      value: initval,
      slide: function( event, ui ) {
        energyIndex = ui.value;
        drawCube4("cvs4", data[energyIndex]);
        drawCube3("cvs3", data[energyIndex]);
        drawCube2("cvs2", data[energyIndex]);
        drawCube1("cvs1", data[energyIndex]);
        updateshgc(data[energyIndex].shgc);
        console.log(data[energyIndex]);
        $($("#slider-vertical").children()[0]).html("<span style=\"left:20px;position:relative;\">"+data[energyIndex].energy.toFixed(1)+"</span>");
      }
    });
    $($("#slider-vertical").children()[0]).html("<span style=\"left:20px;position:relative;\">"+data[energyIndex].energy.toFixed(1)+"</span>");
    updateshgc(data[energyIndex].shgc);

  	$( "#zoomcvs1" ).change(function() {
  		drawCube1("cvs1", data[energyIndex]);
  	});
  	$( "#zoomcvs2" ).change(function() {
  		drawCube2("cvs2", data[energyIndex]);
  	});
    $( "#zoomcvs3" ).change(function() {
      drawCube3("cvs3", data[energyIndex]);
    });
    $( "#zoomcvs4" ).change(function() {
      drawCube4("cvs4", data[energyIndex]);
    });

    drawCube4("cvs4", data[energyIndex]);
    drawCube3("cvs3", data[energyIndex]);
  	drawCube2("cvs2", data[energyIndex]);
  	drawCube1("cvs1", data[energyIndex]);
    $("#initInputInfo").html(
      "Azimuth : " + data[energyIndex].azimuth + " degrees" + "<br>" +
      "WWR : " + data[energyIndex].wwr + " %" + "<br>" +
      "Overhang : " + data[energyIndex].overhang + " m" + "<br>" +
      "Aspect Ratio : " + data[energyIndex].aspectRatio + "<br>"
    );
  }

  init(data);

  var filterInfo = {};

  function filterData(param, val){
    if(param==="glassType"){
      if(typeof val === "string"){
        val=parseFloat(val);
      }
    }
    filterInfo[param] = val;
    applyFiltering(filterInfo);
  }

  function applyFiltering(filterInfo){
    console.log("filtering Info");
    console.log(filterInfo);
    console.log("filtering");
    data=storeData;
    var tempdata=storeData;
    if(filterInfo.glassType){
        tempdata=data;
        data=[];
        var val=filterInfo.glassType;
        for (var i = tempdata.length - 1; i >= 0; i--) {
          // console.log(typeof tempdata[i].shgc + typeof val);
          // console.log(tempdata[i].shgc + " " + val);
          if(val===0){
            data.push(tempdata[i]);
          }
          else if(tempdata[i].shgc===val){
            data.push(tempdata[i]);
          }
        }
      }
      if(filterInfo.azimuth){
        tempdata=data;
        data=[];
        var val=filterInfo.azimuth;
        // console.log("azimuth vals are " + val[0] + " " + val[1]);
        for (var i = tempdata.length - 1; i >= 0; i--) {
          if(tempdata[i].azimuth>=val[0] && tempdata[i].azimuth<=val[1]){
            data.push(tempdata[i]);
          }
        };
      }
      if(filterInfo.aspectRatio){
        tempdata=data;
        data=[];
        var val=filterInfo.aspectRatio;
        // console.log("azimuth vals are " + val[0] + " " + val[1]);
        for (var i = tempdata.length - 1; i >= 0; i--) {
          if(tempdata[i].aspectRatio>=val[0] && tempdata[i].aspectRatio<=val[1]){
            data.push(tempdata[i]);
          }
        };
      }
      if(filterInfo.wwr){
        tempdata=data;
        data=[];
        var val=filterInfo.wwr;
        // console.log("azimuth vals are " + val[0] + " " + val[1]);
        for (var i = tempdata.length - 1; i >= 0; i--) {
          if(tempdata[i].wwr>=val[0] && tempdata[i].wwr<=val[1]){
            data.push(tempdata[i]);
          }
        };
      }
      if(filterInfo.overhang){
        tempdata=data;
        data=[];
        var val=filterInfo.overhang;
        // console.log("azimuth vals are " + val[0] + " " + val[1]);
        for (var i = tempdata.length - 1; i >= 0; i--) {
          if(tempdata[i].overhang>=val[0] && tempdata[i].overhang<=val[1]){
            data.push(tempdata[i]);
          }
        };
      }
      console.log("sizeof data " + data.length);
      init(data);
    }

    function drawCube1(cvsID, data)
    {//topview
      var g = new Cango3D(cvsID),  // create a graphics context
          width = 100,
          colors = ["3399FF", "green", "blue", "yellow", "silver", "sienna"],
          cube, movedCube,
          radius = 50,         // sensitivity of dragging action
          savMouse,
          dragPt,
          csrPt,
          u, theta;

      function grabCube(mousePos)
      {
        savMouse = mousePos;
      }

      function dragCube(mousePos)
      {
        // This drag function rotates an object around its drawing origin
        // assume a lever from drawing origin to drag point z=radius is moved by csr
        var dragPt = {x:savMouse.x-this.grabOfs.x, y:savMouse.y-this.grabOfs.y, z:radius},
            csrPt = {x:mousePos.x-this.grabOfs.x, y:mousePos.y-this.grabOfs.y, z:radius},
            u, theta;

        var incx=0;
        if(mousePos.x - savMouse.x > 0){
          incx++;
        }
        else{
          incx--;
        }
        var incz=0;
        if(mousePos.y - savMouse.y > 0){
          incz++;
        }
        else{
          incz--;
        }
        incx=csrPt.x - dragPt.x;
        incz=csrPt.y - dragPt.y;
        console.log(incx + " " + incz);
        console.log(this.grabOfs);
        console.log(savMouse);
        console.log(mousePos);

        savMouse = mousePos;    // save these as reference for next drag

        cube.translate(-incx, 0, incz);

        // redraw with rotation applied
        g.renderFrame(movedCube);
      }

      g.clearCanvas();
      g.setPropertyDefault("backgroundColor", "lightyellow");
      g.setWorldCoords3D(-150, -100, 400);
      g.setLightSource(0, 0, 200);

      var origin = [0,0,0];

      cube = buildRectShape(g, colors, totalArea, data.azimuth, [data.wwr, data.wwr, data.wwr, data.wwr],
      						data.aspectRatio, data.overhang, 3);
      
      cube.scale($( "#zoomcvs1" ).val()/5);
      //cube = buildCubemanual(g, 100, colors, [0,0,0]);

      // move the cube so cnter is over the drawing origin for nice drag rotation
      //cube.translate(-width/2, -width/2, width/2);

      // enable dragging
      cube.enableDrag(grabCube, dragCube, null);

      // make a group to move the cube independent of turning
      movedCube = g.createGroup3D(cube);
      movedCube.transform.rotate(1, 0, 0, 90);
      movedCube.transform.rotate(0, 1, 0, data.azimuth);

      g.render(movedCube);
    }


    function drawCube2(cvsID, data)
    {
      var g = new Cango3D(cvsID),  // create a graphics context
          width = 100,
          colors = ["3399FF", "green", "blue", "yellow", "silver", "sienna"],
          cube, movedCube,
          radius = 50,         // sensitivity of dragging action
          savMouse,
          dragPt,
          csrPt,
          u, theta;

      function grabCube(mousePos)
      {
        savMouse = mousePos;
      }

      function dragCube(mousePos)
      {
        // This drag function rotates an object around its drawing origin
        // assume a lever from drawing origin to drag point z=radius is moved by csr
        var dragPt = {x:savMouse.x-this.grabOfs.x, y:savMouse.y-this.grabOfs.y, z:radius},
            csrPt = {x:mousePos.x-this.grabOfs.x, y:mousePos.y-this.grabOfs.y, z:radius},
            u, theta;

        savMouse = mousePos;    // save these as reference for next drag
        // axis to rotate lever is the normal to plane defined by the 3 points
        u = calcNormal(this.dwgOrg, dragPt, csrPt);
        // calc angle between dragPt and csrPt (amount of rotation needed about axis 'u')
        theta = calcIncAngle(this.dwgOrg, dragPt, csrPt);    // degrees
        // apply this drag rotation to 'cube' Group3D
        //cube.transform.rotate(u.x, u.y, u.z, theta);
        if(u.y>0){
        	u.y=1;
        }
        else{
        	u.y=-1;
        }
        cube.transform.rotate(0, u.y, 0, theta); //rotates only in the x-z direction
        // redraw with rotation applied
        g.renderFrame(movedCube);
      }

      g.clearCanvas();
      g.setPropertyDefault("backgroundColor", "lightyellow");
      g.setWorldCoords3D(-150, -40, 400);
      g.setLightSource(0, 100, 200);

      var origin = [0,0,0];

      //cube = buildRectShape(g, colors, 10000, 30, [20, 10, 90, 50], 2, 10, 30);
      cube = buildRectShape(g, colors, totalArea, data.azimuth, [data.wwr, data.wwr, data.wwr, data.wwr],
      						data.aspectRatio, data.overhang, 3, true);
      
      cube.scale($( "#zoomcvs2" ).val()/5);
      //cube = buildCubemanual(g, 100, colors, [0,0,0]);

      // move the cube so cnter is over the drawing origin for nice drag rotation
      //cube.translate(-width/2, -width/2, width/2);

      // enable dragging
      cube.enableDrag(grabCube, dragCube, null);

      // make a group to move the cube independent of turning
      movedCube = g.createGroup3D(cube);
      movedCube.transform.rotate(0, 1, 0, data.azimuth);

      g.render(movedCube);
    }


    function drawCube3(cvsID, data)
    {
      var g = new Cango3D(cvsID),  // create a graphics context
          width = 100,
          colors = ["3399FF", "green", "blue", "yellow", "silver", "sienna"],
          cube, movedCube,
          radius = 50,         // sensitivity of dragging action
          savMouse,
          dragPt,
          csrPt,
          u, theta;

      function grabCube(mousePos)
      {
        savMouse = mousePos;
      }

      function dragCube(mousePos)
      {
        // This drag function rotates an object around its drawing origin
        // assume a lever from drawing origin to drag point z=radius is moved by csr
        var dragPt = {x:savMouse.x-this.grabOfs.x, y:savMouse.y-this.grabOfs.y, z:radius},
            csrPt = {x:mousePos.x-this.grabOfs.x, y:mousePos.y-this.grabOfs.y, z:radius},
            u, theta;

        savMouse = mousePos;    // save these as reference for next drag
        // axis to rotate lever is the normal to plane defined by the 3 points
        u = calcNormal(this.dwgOrg, dragPt, csrPt);
        // calc angle between dragPt and csrPt (amount of rotation needed about axis 'u')
        theta = calcIncAngle(this.dwgOrg, dragPt, csrPt);    // degrees
        // apply this drag rotation to 'cube' Group3D
        cube.transform.rotate(u.x, u.y, u.z, theta);
        //cube.transform.rotate(0, 1, 0, theta); //rotates only in the x-z direction
        // redraw with rotation applied
        g.renderFrame(movedCube);
      }

      g.clearCanvas();
      g.setPropertyDefault("backgroundColor", "lightyellow");
      g.setWorldCoords3D(-100, -10, 150);
      g.setLightSource(0, 100, 200);

      var origin = [0,0,0];

      //cube = buildRectShape(g, colors, 10000, 30, [20, 10, 90, 50], 2, 10, 30);
      cube = buildRectShape(g, colors, totalArea, data.azimuth, [data.wwr, data.wwr, data.wwr, data.wwr],
      						data.aspectRatio, data.overhang, 3);
      
      cube.scale($( "#zoomcvs3" ).val()/5);
      //cube = buildCubemanual(g, 100, colors, [0,0,0]);

      // move the cube so cnter is over the drawing origin for nice drag rotation
      //cube.translate(-width/2, -width/2, width/2);

      // enable dragging
      cube.enableDrag(grabCube, dragCube, null);

      // make a group to move the cube independent of turning
      movedCube = g.createGroup3D(cube);
      movedCube.transform.rotate(0, 1, 0, data.azimuth);

      g.render(movedCube);
    }

    function drawCube4(cvsID, data)
    {
      var g = new Cango3D(cvsID),  // create a graphics context
          width = 100,
          colors = ["3399FF", "green", "blue", "yellow", "silver", "sienna"],
          cube, movedCube,
          radius = 50,         // sensitivity of dragging action
          savMouse,
          dragPt,
          csrPt,
          u, theta;

      function grabCube(mousePos)
      {
        savMouse = mousePos;
      }

      function dragCube(mousePos)
      {
        // This drag function rotates an object around its drawing origin
        // assume a lever from drawing origin to drag point z=radius is moved by csr
        var dragPt = {x:savMouse.x-this.grabOfs.x, y:savMouse.y-this.grabOfs.y, z:radius},
            csrPt = {x:mousePos.x-this.grabOfs.x, y:mousePos.y-this.grabOfs.y, z:radius},
            u, theta;

        savMouse = mousePos;    // save these as reference for next drag
        // axis to rotate lever is the normal to plane defined by the 3 points
        u = calcNormal(this.dwgOrg, dragPt, csrPt);
        // calc angle between dragPt and csrPt (amount of rotation needed about axis 'u')
        theta = calcIncAngle(this.dwgOrg, dragPt, csrPt);    // degrees
        // apply this drag rotation to 'cube' Group3D
        cube.transform.rotate(u.x, u.y, u.z, theta);
        //cube.transform.rotate(0, 1, 0, theta); //rotates only in the x-z direction
        // redraw with rotation applied
        g.renderFrame(movedCube);
      }

      g.clearCanvas();
      g.setPropertyDefault("backgroundColor", "lightyellow");
      g.setWorldCoords3D(-40, -10, 200);
      g.setLightSource(0, 100, 200);

      var origin = [0,0,0];

      //cube = buildRectShape(g, colors, 10000, 30, [20, 10, 90, 50], 2, 10, 30);
      cube = buildRectShape(g, colors, totalArea, 0, [0, 0, 0, 0],
                  1, 0, 0.3);
      
      cube.scale($( "#zoomcvs4" ).val()/5);
      //cube = buildCubemanual(g, 100, colors, [0,0,0]);

      // move the cube so cnter is over the drawing origin for nice drag rotation
      //cube.translate(-width/2, -width/2, width/2);

      // enable dragging
      cube.enableDrag(grabCube, dragCube, null);

      // make a group to move the cube independent of turning
      movedCube = g.createGroup3D(cube);
      movedCube.transform.rotate(1, 0, 0, -90);
      g.render(movedCube);
    }

    //here order of wwr is (north, east, south, west)
	function buildRectShape(g, colors, totalArea, azimuth, wwr, aspectRatio, overhangDepth, height, floor) // pass width and array of 6 colors
	{

		var length=Math.sqrt(aspectRatio*totalArea);
		var breadth=totalArea/length;

		var height_of_window=height;//fixing the height of the window to 3; according the given model

		var wwr_height = [];
		var wwr_startz = [];

		wwr_height[0] = wwr[0]/100*height_of_window;
		wwr_startz[0] = height_of_window/2+wwr_height[0]/2;

		wwr_height[1] = wwr[1]/100*height_of_window;
		wwr_startz[1] = height_of_window/2+wwr_height[1]/2;

		wwr_height[2] = wwr[2]/100*height_of_window;
		wwr_startz[2] = height_of_window/2+wwr_height[2]/2;

		wwr_height[3] = wwr[3]/100*height_of_window;
		wwr_startz[3] = height_of_window/2+wwr_height[3]/2;

		var walls = [];
		var totalwalls = 13;
		for (var i = totalwalls; i >= 0; i--) {
			walls[i] = [];
		};
		//side walls
		walls[0][0] = [0, 0, 0];//proper
		walls[0][1] = [0, height, 0];
		walls[0][2] = [length, height, 0];
		walls[0][3] = [length, 0, 0];

		walls[1][0] = [length, 0, 0];//proper
		walls[1][1] = [length, height, 0];
		walls[1][2] = [length, height, breadth];
		walls[1][3] = [length, 0, breadth];

		walls[2][0] = [0, 0, breadth];//proper
		walls[2][1] = [length, 0, breadth];
		walls[2][2] = [length, height, breadth];
		walls[2][3] = [0, height, breadth];

		walls[3][0] = [0, 0, 0];//proper
		walls[3][1] = [0, 0, breadth];
		walls[3][2] = [0, height, breadth];
		walls[3][3] = [0, height, 0];

		//floor proper
		walls[4][0] = [0, 0, 0];
		walls[4][1] = [length, 0, 0];
		walls[4][2] = [length, 0, breadth];
		walls[4][3] = [0, 0, breadth];

		//ceiling proper
		walls[5][0] = [0, height, 0];
		walls[5][1] = [0, height, breadth];
		walls[5][2] = [length, height, breadth];
		walls[5][3] = [length, height, 0];

		//overhang wall1
		walls[6][0] = [0, wwr_startz[0], 0];
		walls[6][1] = [length, wwr_startz[0], 0];
		walls[6][2] = [length, wwr_startz[0], -overhangDepth];
		walls[6][3] = [0, wwr_startz[0], -overhangDepth];

		walls[7][0] = [length, wwr_startz[1], 0];
		walls[7][1] = [length, wwr_startz[1], breadth];
		walls[7][2] = [length+overhangDepth, wwr_startz[1], breadth];
		walls[7][3] = [length+overhangDepth, wwr_startz[1], 0];

		walls[8][0] = [length, wwr_startz[2], breadth];
		walls[8][1] = [0, wwr_startz[2], breadth];
		walls[8][2] = [0, wwr_startz[2], breadth+overhangDepth];
		walls[8][3] = [length, wwr_startz[2], breadth+overhangDepth];

		walls[9][0] = [0, wwr_startz[3], breadth];
		walls[9][1] = [0, wwr_startz[3], 0];
		walls[9][2] = [-overhangDepth, wwr_startz[3], 0];
		walls[9][3] = [-overhangDepth, wwr_startz[3], breadth];

		var smallinc = 0.01;
		//windows
		walls[10][0] = [0, wwr_startz[0], 0-smallinc];
		walls[10][1] = [length, wwr_startz[0], 0-smallinc];
		walls[10][2] = [length, wwr_startz[0]-wwr_height[0], 0-smallinc];
		walls[10][3] = [0, wwr_startz[0]-wwr_height[0], 0-smallinc];

		walls[11][0] = [length+smallinc, wwr_startz[1], 0];
		walls[11][1] = [length+smallinc, wwr_startz[1], breadth];
		walls[11][2] = [length+smallinc, wwr_startz[1]-wwr_height[1], breadth];
		walls[11][3] = [length+smallinc, wwr_startz[1]-wwr_height[1], 0];

		walls[12][0] = [length, wwr_startz[2], breadth+smallinc];
		walls[12][1] = [0, wwr_startz[2], breadth+smallinc];
		walls[12][2] = [0, wwr_startz[2]-wwr_height[2], breadth+smallinc];
		walls[12][3] = [length, wwr_startz[2]-wwr_height[2], breadth+smallinc];

		walls[13][0] = [0-smallinc, wwr_startz[3], breadth];
		walls[13][1] = [0-smallinc, wwr_startz[3], 0];
		walls[13][2] = [0-smallinc, wwr_startz[3]-wwr_height[3], 0];
		walls[13][3] = [0-smallinc, wwr_startz[3]-wwr_height[3], breadth];

    if(floor===true){
      totalwalls++;
      walls[totalwalls]=[];
      flen=10;
      fbred=10;
      walls[14][0] = [-flen, -smallinc,  -flen];
      walls[14][1] = [ flen, -smallinc,  -flen];
      walls[14][2] = [ flen, -smallinc,   flen];
      walls[14][3] = [-flen, -smallinc, flen];
    }

	  	var sq=[];
	    var colorNum = 4;
	    var  faces = g.createGroup3D(),
	      side;

	  	for (var i = walls.length - 1; i >= 0; i--) {
	  		if(i>=10){
	  			colorNum=0;
	  		}
	  		else{
	  			colorNum=4;
	  		}
		  	sq[i] = ['M',walls[i][0][0], walls[i][0][1], walls[i][0][2], 'L',walls[i][1][0],walls[i][1][1],walls[i][1][2],
		  	walls[i][2][0], walls[i][2][1], walls[i][2][2], walls[i][3][0], walls[i][3][1], walls[i][3][2], 'z'];
		    side = g.compileShape3D(sq[i], colors[colorNum]);
        faces.addObj(side);
	  	};

	  return faces;
	}

$(function()
{
	$.each( $(".ctab-pane"), function( key, value ) {
			$(this).addClass("tab-pane");
	});
});

	</script>

