<style type="text/css">
.irs-min, .irs-max{display:none !important}
.min, .max{width:50px}
.min{float:left}
.max{float:right}
.control-label{clear:both;display:block}
</style>
<?php //print_r($user_glass_types); ?>
<img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/mlogo.png" alt="logo" class="logo-default"/>
<div STYLE="width:400px;float:right">
<?php if($user = $this->identity()) { ?> 
    <a href="<?php echo $this->url('user-index');?>" class="btn btn-success">
      <?php echo $this->translate('User Home'); ?>
    </a>
	<a href="<?php echo $this->url('user-register', array('action' => 'edit-profile'));?>" class="btn btn-success">
	  <?php echo $this->translate('Edit Profile'); ?>
	</a> 
	<a href="<?php echo $this->url('user-index', array('action' => 'logout'))?>" class="btn btn-success">
	  <?php echo $this->translate('Log Out'); ?>
	</a>
<?php
  } else { ?>
	<a href="<?php echo $this->url('user-index', array('action' => 'login'))?>" class="btn btn-success">
	  <?php echo $this->translate('Log in'); ?>
	</a>
	<a href="<?php echo $this->url('user-register');?>" class="btn btn-success">
	  <?php echo $this->translate('Sign Up'); ?>
	</a>
	<a href="<?php echo $this->url('user-register', array('action' => 'reset-password'));?>" class="btn btn-success">
	  <?php echo $this->translate('Reset Password'); ?>
	</a>
<?php } ?>
</div>
			
		
		<div class="portlet-body form" style="clear:both">
			<input type="hidden" id="cmin" />
			<input type="hidden" id="cmax" />
			<form role="form">

			<div class="form-group" style="float:left">
				<div style="display:inline-block;margin-left:10px">	
					<label class="control-label">Location</label><div style="clear:both"></div>
					<select style="display:inline-block" class="input-small">
						<option>Option 1</option>
						<option>Option 2</option>
						<option>Option 3</option>
						<option>Option 4</option>
						<option>Option 5</option>
					</select>
				</div>
				
			
				<div style="display:inline-block;margin-left:10px">
					<label class="control-label">Plot Length</label><div style="clear:both"></div>
					<div style="display:inline-block">
						<input type="text" class="input-small" >
					</div>
				</div>
				
				<div style="display:inline-block;margin-left:10px">
					<label class="control-label">Plot Width</label><div style="clear:both"></div>
					<div style="display:inline-block">
						<input type="text" class="input-small" >
					</div>
				</div>
				
				<div style="display:inline-block;margin-left:10px">
					<label class="control-label">Building Area</label><div style="clear:both"></div>
					<div style="display:inline-block">
						<input type="text" class="input-small" >
					</div>
				</div>
				
				<div style="display:inline-block;margin-left:10px">	
				<label class="control-label">AC Type</label><div style="clear:both"></div>
					<select style="display:inline-block" class=" input-small">
						<option>Option 1</option>
						<option>Option 2</option>
						<option>Option 3</option>
						<option>Option 4</option>
						<option>Option 5</option>
					</select>
				</div>
			</div>
			
			
			
			<div style="clear:both"></div>
			
			<div class="form-group">
				<div style="display:inline-block;margin-left:10px">
					<label class="control-label">Day Light Controls</label><div style="clear:both"></div>
					<div class="actions" style="display:inline-block">
								<input type="checkbox" class="make-switch" checked data-size="small" data-on="success" data-off="warning">
					</div>
				</div>
				
				<div style="display:inline-block;margin-left:10px">
					<label class="control-label">Internal Shading Controls</label><div style="clear:both"></div>
					<div class="actions" style="display:inline-block">
						<select style="display:inline-block" class=" input-small">
						<option>No shading controls</option>
						<option>temperature shading</option>
						<option>Roof Shading</option>
					</select>		
					</div>
				</div>
				
				<div style="display:inline-block;margin-left:10px">
					<div class="checkbox">
						<label><input type="checkbox" id="croof"> Cool Roof </label><div style="clear:both"></div>
					</div>
				</div>
			</div>
			
			</form>
			
		</div>

			<div style="clear:both"></div>
			
			<div class="row" style="margin-top:50px">
			
				<div class="col-md-6">
					<div class="portlet box blue-steel">
						<div class="portlet-title">
							<div class="caption">
								Define
							</div>
						</div>

				
						<div class="portlet-body">
							<div class="form-group">
								<label class="control-label"><strong>Azimuth</strong> <span style="float:right" class="lock" id="1"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
								<div id="range_1_box">
									<input type="text" value="" id="range_1-min" class="min" />
									<input type="text" value="" id="range_1-max" class="max" />
									<br/><br/>
									<input id="range_1" type="text" name="range_1" value=""/>
								</div>
								<div id="range_1_text" style="display:none">
									<input type="text" name="range_1" value=""/>
								</div>
							</div>
							
							<div class="form-group">
								<label class="control-label"><strong>Aspect Ratio</strong>  <span style="float:right" class="lock" id="2"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
								<div id="range_2_box">
									<input type="text" value="" id="range_2-min" class="min" />
									<input type="text" value="" id="range_2-max" class="max" />
									<br/><br/>
									<input id="range_2" type="text" name="range_2" value=""/>
								</div>
								<div id="range_2_text" style="display:none">
									<input type="text" name="range_2" value=""/>
								</div>
							</div>
							
							<div class="form-group">
								<label class="control-label"><strong>Overhang</strong>  <span style="float:right" class="lock" id="4"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
								<div id="range_4_box">
									<input type="text" value="" id="range_4-min" class="min" />
									<input type="text" value="" id="range_4-max" class="max" />
									<br/><br/>
									<input id="range_4" type="text" name="range_4" value=""/>
								</div>
								<div id="range_4_text" style="display:none">
									<input type="text" name="range_4" value=""/>
								</div>
							</div>

							
							<div class="form-group">
								<label class="control-label"><strong>Window to Wall Ratio</strong>  </label><div style="clear:both"></div>
										<div class="radio-list">
											<label>
											<input type="radio" name="optionsRadios" id="wwr" class="wwr" value="same_dir" checked> Same in all directions</label><div style="clear:both"></div>
											<label>
											<input type="radio" name="optionsRadios" id="wwr2" class="wwr" value="different_dir"> Different in all directions </label><div style="clear:both"></div>
										</div>
								<div id="swwr">
									<span style="float:right" class="lock" id="3"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span>
									<br/><br/>
									<div id="range_3_box">
										<input type="text" value="" id="range_3-min" class="min" />
										<input type="text" value="" id="range_3-max" class="max" />
										<br/><br/>
										<input id="range_3" type="text" name="range_3" value=""/>
									</div>
									<div id="range_3_text" style="display:none">
										<input type="text" name="range_3" value=""/>
									</div>
								</div>
								
								<div id="dwwr">
									<label class="control-label">Front WWR:- <span style="float:right" class="lock" id="3_1"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
									<div id="range_3_1_box">
										<input type="text" value="" id="range_3_1-min" class="min" />
										<input type="text" value="" id="range_3_1-max" class="max" />
										<br/><br/>
											<input id="range_3_1" type="text" name="range_3_1" value=""/>
									</div>
									<div id="range_3_1_text" style="display:none">
										<input type="text" name="range_3_1" value=""/>
									</div>
									<br/>
									
									<label class="control-label">Back WWR:-	<span style="float:right" class="lock" id="3_2"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
									<div id="range_3_2_box">
											<input type="text" value="" id="range_3_2-min" class="min" />
										<input type="text" value="" id="range_3_2-max" class="max" />
										<br/><br/>
											<input id="range_3_2" type="text" name="range_3_2" value=""/>
									</div>
									<div id="range_3_2_text" style="display:none">
										<input type="text" name="range_3_2" value=""/>
									</div>
									<br/>
								
									<label class="control-label">Left WWR:-	<span style="float:right" class="lock" id="3_3"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
									<div id="range_3_3_box">
											<input type="text" value="" id="range_3_3-min" class="min" />
										<input type="text" value="" id="range_3_3-max" class="max" />
										<br/><br/>
											<input id="range_3_3" type="text" name="range_3_3" value=""/>
									</div>
									<div id="range_3_3_text" style="display:none">
										<input type="text" name="range_3_3" value=""/>
									</div>
									<br/>
									
									<label class="control-label">Right WWR:- <span style="float:right" class="lock" id="3_4"><img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/lock.png" /></span></label><div style="clear:both"></div>
									<div id="range_3_4_box">
										<input type="text" value="" id="range_3_4-min" class="min" />
										<input type="text" value="" id="range_3_4-max" class="max" />
										<br/><br/>
										<input id="range_3_4" type="text" name="range_3_4" value=""/>
									</div>	
									<div id="range_3_4_text" style="display:none">
										<input type="text" name="range_3_4" value=""/>
									</div>
								 </div>
											
							</div>
														
							<div class="form-group">
								<label class="control-label"><strong>Glass Type</strong> </label><div style="clear:both"></div>
								No of Selections:- <select id="us" style="display:inline-block" class=" input-small">
									<?php
									for($i = 1; $i <=15; $i++)
									{
									?>
										<option><?php echo $i; ?></option>
									<?php
									}
									?>
								</select>
								<?php
									//mysql_connect("need4all.com.mysql", "need4all_com", "MeetvMysql");
									//mysql_select_db("need4all_com");
									//$result = mysql_query("SELECT * FROM `user_glass_types` WHERE `user_id` = 1");
								?>
								<br/><br/>User Glass Types:- 
								<div style="clear:both;height:10px"></div>			
								
								<div class="col-xs-5">
									<select name="from" id="multiselect" class="form-control" size="8" multiple="multiple">
										<?php
										foreach($user_glass_types as $ug)
										{
										?>
											<option value="<?php echo $ug->glass_id; ?>"><?php echo $ug->name; ?></option>
										<?php
										}
										?>
									</select>
								</div>
								
								<div class="col-xs-2" style="margin-top:50px">
									<button type="button" id="multiselect_rightSelected" onclick="return false" class="btn btn-block">Add</button>
									<button type="button" id="multiselect_leftSelected" class="btn btn-block">Remove</button>									
								</div>
								
								<div class="col-xs-5">
									<select name="to" id="multiselect_to" class="form-control" size="8" multiple="multiple"></select>
								</div>
							</div>
							
					<div style="clear:both;height:10px"></div>			
					<div class="portlet box yellow">
						<div class="portlet-title">
							<div class="caption">
								Roof Type
							</div>
							<div class="tools">
								<a href="javascript:;" class="expand">
								</a>
							
							</div>
						</div>
						<div class="portlet-body"   style="display:none">
							<div class="tabbable-custom ">
								<div style="">	
									<label class="control-label">Layer 1</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 2</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 3</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 4</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div id="coolroof" style="display:none">
								
									<h2>Cool Roof</h2>
									<div style="">	
									<label class="control-label">Layer 1</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 2</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 3</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 4</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>

								
								</div>
							
							</div>
						</div>
					</div>
					
					<div class="portlet box yellow">
						<div class="portlet-title">
							<div class="caption">
								Wall Type
							</div>
							<div class="tools">
								<a href="javascript:;" class="expand">
								</a>
							
							</div>
						</div>
						<div class="portlet-body"  style="display:none">
							<div class="tabbable-custom">
								<div style="">	
									<label class="control-label">Layer 1</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 2</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 3</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
								
								<div style="">	
									<label class="control-label">Layer 4</label><div style="clear:both"></div>
									<select style="display:inline-block" class="input-small layers">
										<option value="F08 Metal surface">      Metal Surface         </option>
										<option value="12mm Thick Mortar" selected="">      12mm thick motar       </option>
										<option value="F13 Built-up roofing">      Built-up roofing      </option>
										<option value="150mm Thick RCC Slab">      150mm Thick RCC Slab      </option>
										<option value="200mm Thick RCC Slab">      200mm Thick RCC Slab      </option>
										<option value="Gypsum Plasterboard">      Gypsum Plasterboard      </option>
										<option value="F14 Slate or tile">      Tile or slate      </option>
										<option value="F16 Acoustic tile">      Acoustic tile      </option>
										<option value="Insulation">     Insulation     </option>
									</select>
								</div>
							
							</div>
						</div>
					</div>
					
					<div id="r5">
							<div id="range_5_box">
								<input type="text" value="" id="range_5-min" class="min" />
								<input type="text" value="" id="range_5-max" class="max" />
								<br/><br/>
								<input id="range_5" type="text" name="range_4" value=""/>
							</div>
							<div id="range_5_text" style="display:none">
								<input type="text" name="range_5" value=""/>
							</div>
					</div>	
					
							<div class="form-group" Style="text-align:center">
								<button type="submit" class="btn blue">Submit</button>
								<button type="submit" style="margin-left:30px" class="btn blue">Reset All</button>
							</div>
						</div>
						
						
					</div>
				</div>
				
				<div class="col-md-6" >
					<div class="portlet-body">
						<ul class="nav nav-tabs" style="margin-bottom:0px">
							<li class="active">
								<a href="#tab_1_1" data-toggle="tab">
								3D View </a>
							</li>
							<li>
								<a href="#tab_1_2" data-toggle="tab">
								Plan </a>
							</li>
							<li >
								<a href="#tab_1_3" data-toggle="tab">
								Elevation
								</a>
							</li>
							
							<li>
								<a href="#tab_1_4" data-toggle="tab">
								Glass Properties
								</a>
							</li>
						</ul>
						<div class="tab-content"   style="border:1px solid #ddd;border-top:none;height:985px">
							<div class="tab-pane fade active in" id="tab_1_1">
								
								
								
									<div class="portlet light bordered">
								<div class="portlet-title">
									<div class="caption">
										<i class="icon-bar-chart font-green-haze"></i>
										<span class="caption-subject bold uppercase font-green-haze"> Line & Area</span>
										<span class="caption-helper">duration on value axis</span>
									</div>
									<div class="tools">
										<a href="javascript:;" class="collapse">
										</a>
										<a href="#portlet-config" data-toggle="modal" class="config">
										</a>
										<a href="javascript:;" class="reload">
										</a>
										<a href="javascript:;" class="fullscreen">
										</a>
										<a href="javascript:;" class="remove">
										</a>
									</div>
								</div>
								<div class="portlet-body">
									<div id="chart_2" class="chart" style="height: 400px;">
									</div>
								</div>
							</div>
							
										
										
										
							</div>
							<div class="tab-pane fade" id="tab_1_2">
								
							</div>
							<div class="tab-pane fade" id="tab_1_3">
								
							</div>
							<div class="tab-pane fade" id="tab_1_4">
								
							</div>
						</div>
					</div>
				</div>
				
			</div>
			
			
			