<style type="text/css">
.irs-min, .irs-max{display:none !important}
.min, .max{width:50px}
.min{float:left}
.max{float:right}
.control-label{clear:both;display:block}
</style>
<img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/mlogo.png" alt="logo" class="logo-default"/>
<?php
echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

?>

<?php
//print_r($glass_types);
?>			
		
		<div class="portlet-body form">
		<form action="" method="post">
<br/><br/>User Glass Types:- 
								<div style="clear:both;height:10px"></div>			
								
								<div class="col-xs-5">
									<select name="from" id="multiselect" class="form-control" size="8" multiple="multiple">
										<?php
										foreach($glass_types as $gt)
										{
											

										?>
											<option value="<?php echo $gt->id; ?>"><?php echo $gt->name; ?></option>
										<?php
										}
										?>
									</select>
								</div>
								
								<div class="col-xs-2" style="margin-top:50px">
									<button type="button" id="multiselect_rightSelected" class="btn btn-block">Add</button>
									<button type="button" id="multiselect_leftSelected" class="btn btn-block">Remove</button>									
								</div>
								
								<div class="col-xs-5">
									<select name="to[]" id="multiselect_to" class="form-control" size="8" multiple="multiple"></select>
								</div>
								
								<input type="submit" value="Save" />
				</form>
			</div>