<style type="text/css">
.irs-min, .irs-max{display:none !important}
.min, .max{width:50px}
.min{float:left}
.max{float:right}
.control-label{clear:both;display:block}
</style>
<img src="<?php echo $this->basePath(); ?>/assets/admin/layout/img/mlogo.png" alt="logo" class="logo-default"/>
<?php
echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

?>

<?php
//print_r($glass_types);
?>			
		
		<div class="portlet-body form">
		<form action="" method="post">
<br/><br/>Projects:- 
			<div style="clear:both;height:10px"></div>			

					<div class="col-xs-5">
					Name:-
						<input type="text" name="name" value="" />
					</div>
					</div>

					
			<input type="submit" value="Save" />
				</form>
			</div>